server:
  servlet:
    context-path: /base
  port: 80

#库配置
database:
  base:
    driver: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/db_base?useSSL=false

#redis
spring:
  redis:
    host: 192.168.78.100
    password:
    port: 6379
    database: 1
    timeout: 1000ms
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1ms
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
        #连接超时时间
